config/routes.rb
Vennsongs::Application.routes.draw do
  resources :songs
  root :to => 'venn#bubble'
  get '(/:action(/:id))', to: 'venn'

  root :to => 'venn#bubble'

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :artist, :critic, :rank, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  respond_to :html, :js, :json
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        @songs_count = Song.count
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.js
        format.json { render json: @song, status: :created, location: @song }
      else
        @songs_count = Song.count
        format.html { render action: "new" }
        format.js
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/venn_controller.rb
class VennController < ApplicationController
  respond_to :html, :json

  def index
    #@songs_by_critic = Song.select("critic, count(*) as tally").group("critic")
    @songs_by_critic = Song.select("title as name, count(*) as size").group("title")
    respond_to do |format|
      format.json { render json: @songs_by_critic }
      format.html
    end
  end

  def bubble
  	params[:critics] ||= []
    @songs_by_critic = Song.select("critic, count(*) as size").group("critic")
    if params[:critics].empty?
	    @songs_by_artist = Song.select("artist as name, count(*) as size").
	    	order("count(*) DESC").group("artist")
    else
    	@songs_by_artist = Song.select("artist as name, count(*) as size").
    		where("critic IN (:critics)",{critics: params[:critics]}).order("count(*) DESC").group("artist")
  	end

    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vennsongs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="http://d3js.org/d3.v3.min.js"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" id="container">
<%= yield %>
</div>
</body>
</html>

app/views/songs/_form.html.erb
<tr id="new-song-row">
<%= form_for(@song, :remote => true) do |f| %>
  <% if @song.errors.any? %>
  <td colspan="5">
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </td>
  </tr>
  <tr>
  <% end %>
  <td>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :critic %><br />
    <%= f.text_field :critic %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.number_field :rank %>
  </div>
  </td>
  <td>
  <div class="actions">
    <%= f.submit %>
  </div>
  </td>
<% end %>
</tr>

app/views/songs/_song.html.erb
<tr id="<%= dom_id(song) %>"><td><%= link_to song.title, song %></td><td><%= song.artist %></td><td><%= song.critic %></td><td><%= song.rank %></td></tr>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1 >Listing <span id="song-count"><%= @songs.count %></span> songs</h1>

<table id="songs">
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Critic</th>
    <th>Rank</th>
  </tr>

<%= render @songs %>
</table>

<div id="new-song">
  <%= link_to 'New Song', new_song_path, remote: true %>
</div>

app/views/songs/new.html.erb
<%= render 'form' %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @song.title %>
</p>

<p>
  <b>Artist:</b>
  <%= @song.artist %>
</p>

<p>
  <b>Critic:</b>
  <%= @song.critic %>
</p>

<p>
  <b>Rank:</b>
  <%= @song.rank %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/venn/_bubble_chart.html.erb
<div id="chart">
</div>

<script>
var json = 
{
   "name": "analytics",
     "children": <%= raw @songs_by_artist.to_json %>
  };

var r = 1060,
    format = d3.format(",d"),
    fill = d3.scale.category20c();

var bubble = d3.layout.pack()
    .sort(null)
    .size([r, r])
    .padding(1.0);

var vis = d3.select("#chart").append("svg")
    .attr("width", r)
    .attr("height", r)
    .attr("class", "bubble");


  var node = vis.selectAll("g.node")
      .data(bubble.nodes(classes(json))
      .filter(function(d) { return !d.children; }))
    .enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });

  node.append("title")
      .text(function(d) { return d.className + ": " + format(d.value); });

  node.append("circle")
      .attr("r", function(d) { return d.r; })
      .style("fill", function(d) { return fill(d.packageName); });

  node.append("text")
      .attr("text-anchor", "middle")
      .attr("dy", ".3em")
      .text(function(d) { return d.className.substring(0, d.r / 3); });

// Returns a flattened hierarchy containing all leaf nodes under the root.
function classes(root) {
  var classes = [];

  function recurse(name, node) {
    if (node.children) node.children.forEach(function(child) { recurse(node.name, child); });
    else classes.push({packageName: name, className: node.name, value: node.size});
  }

  recurse(null, root);
  return {children: classes};
}
</script>

app/views/venn/bubble.html.erb
<div id="critics" style="padding-top: 20px; width:90%; margin-left:auto; margin-right:auto; font-size: 1.2em;">
<strong>Critics</strong><br/>
<div id='critic-list'>
<% selected_critics = []
   selected_critics = params[:critics] unless params[:critics].empty? %>
<% @songs_by_critic.each do |critic|
  critic_class = "critic"
  critic_class << " selected" if (params[:critics].empty? || params[:critics].include?(critic.critic))
  if selected_critics.include?(critic.critic)
    critics = selected_critics - [critic.critic]
  else
    critics = selected_critics + [critic.critic]
  end
  %>
  <%= link_to critic.critic, {controller: 'venn', action: 'bubble', critics: critics}, {class: critic_class} %>&nbsp;&nbsp;
<% end %>
</div>
</div>
<%= render "bubble_chart" %>

app/views/venn/index.html.erb
<h2>Critics</h2>
<script lang="text/javascript">
<%= raw render "graph" %>
</script>